src/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup_view, name = 'signup'),
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
]

src/blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blogapp'
urlpatterns = [
    path('', views.article_list, name = 'list'),
    path('create/', views.article_create, name = 'create'),
    path('(?P<slug>[\w-]+)/', views.article_detail, name = 'detail'),
]

src/blogsite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('blogapp/', include('blogapp.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()

src/accounts/models.py
from django.db import models

# Create your models here.

src/blogapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 200)
    slug = models.SlugField(unique=True)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, default = None, on_delete=models.DO_NOTHING)


    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.body[:50]+'...'
    
    

src/blogapp/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug']

src/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout



# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('blogapp:list')
            #log the user in
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('blogapp:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('blogapp:list')
    

src/blogapp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
    #return HttpResponse("I'm in the views page")
    articles = Article.objects.all().order_by('date')
    return render(request, 'blogapp/article_list.html', {'articles':articles})

def article_detail(request, slug):
    #return render(request, 'blogapp/detail.html')
    article = Article.objects.get(slug=slug)
    return render(request, 'blogapp/article_detail.html', {'article':article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user 
            form.save()
            return redirect('blogapp:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'blogapp/article_create.html', {'form':form})

src/blogsite/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

src/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h2>Login Page</h2>
        <form class="site-form" action="/accounts/login/" method="POST">
            {% csrf_token %}
            {{ form }}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            <input type="Submit" value="Login">
        </form>
{% endblock %}

src/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h2>Signup Page</h2>
        <form class="site-form" action="/accounts/signup/" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="Submit" value="Sign Up">
        </form>
{% endblock %}  

src/blogapp/templates/blogapp/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h1>Create a new Article</h1>
            <form class="site-form" action="/blogapp/create/" method="POST">
                {% csrf_token %}
                {{ form }} 
                <input type="submit" value="Create">
            </form>
    </div>
{% endblock %} 

src/blogapp/templates/blogapp/article_detail.html
{% extends 'base_layout.html' %}


{% block content %}
    <div class="article-detail">
        <div class="article">
            <h2>{{article.title}}</h2>
            <p>{{article.body}}</p>
            <p>{{article.date}}</p>
            <p>Posted by {{article.author}}</p>
        </div>
    </div>
{% endblock %}

src/blogapp/templates/blogapp/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="articles">
        {%for article in articles%}
            <div class="article">
                <h2><a href="{% url 'blogapp:detail' slug=article.slug %}">{{article.title}}</a></h2>
                <p>{{article.snippet}}</p>
                <p>{{article.date}}</p>
            </div>
        {%endfor%}
    </div>
{% endblock %}

src/templates/base_layout.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Articles</title>
</head>
<body>
    <div class="wrapper">
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form action="{% url 'accounts:logout' %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" value="Logout">
                    </form>
                </li>
                <li><a href="{% url 'blogapp:create' %}">Create Article</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Sign up</a></li>
                {% endif %}
            </ul>
        </nav>
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

src/templates/homepage.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>This is my Homepage</h1>
    <p>I've created the damn shit and if you don't believe me you can kiss my fucken ass</p>
{% endblock %}